server:
  port: 8080

logging:
  level:
    com.itheima: debug
  pattern:
    dateformat: HH:mm:ss
#yaml中固定写法:
knife4j:
  enable: true
  openapi:
    title: "用户管理接口文档"
    description: 用户管理接口文档
    email: zhanghuyi@itcast.cn
    concat: 虎哥
    url: https"//www.itcast.cn
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.itheima.controller
#连接数据库
spring:
  datasource:
    url: jdbc:mysql:///mp?serverTimezone=UTC
    username: root
    password: 315617
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis原生配置
mybatis-plus:
  type-aliases-package: com.itheima.pojo #别名包扫描
  mapper-locations: classpath*:mapper/*.xml #mapper.xml文件路径
  configuration:
    map-underscore-to-camel-case: true #开启下划线驼峰
    cache-enabled: false #二级缓存
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.JacksonTypeHandler
  global-config:
    db-config:
      id-type: auto
      update-strategy: not_null #只更新非空字段
      logic-delete-field: flag
      logic-delete-value: 1
      logic-not-delete-value: 0